### PR TITLE
Added Slovenian language

### PR DESCRIPTION
**Pull request by mytja**
Added partly Slovenian language and fixed some mistakes in English language.

1. I like your project, but isn't this some kind of piracy?
2. For me, search button didn't work and search UI is a little bit confusing!
3. Can you tell me about this translation?:
static const String STRING_SEARCH_RESULT_TOP_BUTTON_LABEL_0_ALBUM          = 'DOWNLOAD ALBUM';
  static const String STRING_SEARCH_RESULT_TOP_BUTTON_LABEL_0_TRACK          = 'DOWNLOAD TRACK';
  static const String STRING_SEARCH_RESULT_TOP_BUTTON_LABEL_0_ARTIST         = 'DOWNLOAD TRACKS';
_TRACK and _ARTIST are same????

! NOTE ! Do not merge until I say so! There is only a part of translations. More of them are comming soon.
I didn't understand completly this translating process, so I'm going to allow edits!

Thank you
Mytja

### CODE REVIEW

**Comment by alexmercerind** [comment]
Hi @mytja!
Okay... Definitely. I will give you my backend code (It's in Python and uses Flask). It's in a private repository currently and I'll write a bit of README for you to understand. And then you can also use it, the way you want.
Apart from that, is the music playback/download working fine for you in the app?
I have deployed it on heroku for this app.

**Comment by mytja** [comment]
For me, everything works fine.
I once upon a time used app called Free Music 2020, which downloaded music from YouTube, and required a lot of permissions. And it downloaded music without compression, so it filled 4 MB of storage, 40 if I downloaded MP4 file.
I can garantee that your app is better. Just everything... UI, search is faster, downloading is faster...
However, where do you save your downloads, if you don't want folder permissions?
Do you think, that once, your app will be submitted to app store?
Hope that my feedback will help you.

**Comment by alexmercerind** [comment]
Hi @mytja !

I made a new repository for the backend of this app [here](https://github.com/alexmercerind/harmonoid-service). You can use this if you want to. (It's very badly written 😓)

(In future I have planned to add option for setting custom backend link in the app.)

Thanks a lot for your kind words. I'm really glad.

Yeah... It does not require any storage permissions because, Android itself provides some storage to the app for 'App cache & data'... But one cannot read/write any random file on system. Without storage permissions, an app can write files inside ```Android/data/<APP-NAME>/files``` only
So I store tracks there. (This feature of Android surprised me aswell, but it makes this app safe.)

**Comment by mytja** [comment]
Done!
Here are my deployed servers:
https://harmonoid-eu.herokuapp.com/
https://harmonoid-us.herokuapp.com/
You can integrate them in your app.

**Comment by mytja** [comment]
And what I like about your app is, that it comes with background music playing. I love that!
I searched for app that could do the same, before I found your app, and didn't find anything!
:-)

**Comment by alexmercerind** [comment]
Hello @mytja !
Thanks a lot for your kind words. I'm very glad.

Actually at the moment, I don't need a secondary server. Another thing that I wanna say is that I transferred the ownership of the Python back-end of this app to @raitonoberu. He was willing to improve it's performance and functioning.

Yeah! You have to get your own client ID & secret (and keep it secret to yourself aswell) for setting up the back-end. You can un-deploy your servers at the moment. (Mine server is running fine... currently for debugging, development and basic usage currently). Thanks a lot for taking an interest in the project.

Yeah, I'm also very 😃 happy for the background playback, it took a lot of time to setup... (I'm using @ryanheise 's amazing libraries **just_audio** & **audio_service** for this app. His libraries helped this project a lot.)

Today I'll push some changes to this repo, which will add language switching.

**Comment by alexmercerind** [comment]
Hi @mytja!

I've merged your PR (your contribution now in this file.)

You're now mentioned in the 'contributors' of the app. Thanks for your contribution. 😊

https://github.com/alexmercerind/harmonoid/blob/f8e4f357f1d68e8a4da3075e763fe4e874062155/lib/scripts/globalsupdater.dart#L144-L211

**Comment by mytja** [comment]
You're welcome!

**Pull request merged**
