### PR TITLE
Added some new things and Slovenian language

### PR DESCRIPTION
**Pull request by mytja**
Hello, @alexmercerind 
I translated some new translations and retranslated some bad translations. :+1: 
I also added free to use servers. You can remove that if you want.
Since you now enabled option of deploying your own servers, so I thought, that we have to add one sentence to existing sentences:
https://github.com/mytja/harmonoid/blob/80205b44b941d8060f5ca1c63530a079499ed4cf/lib/scripts/globalsupdater.dart#L56
`You can change server URL in settings and try if it works.`
I added this part to other languages, can you please notify others while translating not to forget it, since it's kind of hidden.
Sorry, but I got completly confused with adding this part to Hindi :smile: , can you please do that?
Thank you so much

### CODE REVIEW

**Comment by mytja** [comment]
And also @raitonoberu and @alexmercerind can you please fix in README, it your servers are in wrong part (region or service). I didn't know, so I went with most commonly used parts (Youtube Music @ US)
Thank you

**Comment by mytja** [comment]
Sorry, that I'm marking it as draft quite often, but I always forget something, and that you wouldn't merge during my fixing... :smile:

**Comment by raitonoberu** [comment]
Hi guys!
@mytja, I like your ideas. I was also thinking about adding a list of free to use servers. `harmonoid-ru` is EU server, `harmonoid` (as far as I know) is alexmercerind`s development server (might be unstable too). And I think Youtube Music servers should be higher than Spotify servers, since they are the main ones

**Comment by alexmercerind** [comment]
Okay,

But the thing is that I've completely de-branded the project from Spotify or YouTube. Now it's just a app that GETS INFORMATION FOR ITSELF FROM A SERVER WRITTEN IN A VERY SPECIFIC WAY & DISPLAYS IT TO THE USER. THE SERVER CAN BE WRITTEN BY THE PERSON HIMSELF OR USE IT FROM THE SOURCE.
Because it is just not okay for an independent app like this to exist which can give copyrighted music for free. (It will be classified as a service & non-personal then)

As I said few days ago, YouTube is a site for personal & non-commercial usage. But, making a public server does not "keeps it personal" anymore.

**So, what do you mean? Is it illegal for harmonoid to exist?**
"Owning a gun is not illegal but, killing someone can definitely cause you some legal problems"

Similarly, projects like youtube-dl exist, because YouTube cannot sue them, otherwise it's maintainer would have stopped working. It's just "a code" written to fetch audio/video streams over the internet.

It is "okay" for projects like youtube-dl to exist independently because those are not full-fledged apps to be used by end user but, they are just projects (not service)... like "A random guy posted his code saying, this is how the things can be done".
When people use youtube-dl, they are just using "a code" to get information from YouTube & using it personally. One cannot say that it is that fault of youtube-dl maintainer to make youtube-dl. youtube-dl maintainer just posted his code on GitHub, it is not a compiled binary for people, people use it themselves (that is another matter however that Python is interpreted language).
When someone uses youtube-dl, it is acceptable that requests are being made on his own personal computer or so & he will just use the downloaded content him/her self or with his/her friends/family. And youtube-dl is not a service, it's a bunch of code written by a stranger on internet, so it is okay for it to exist. 

**So what are you going to do?**

In case of this app (right now), we are just handling network requests on a unified server & providing the copyrighted music to the users as a service, which no longer can be classified as personal use.

Hopefully, my plan it is to take down all of my servers & ask users to run/deploy their own (they can write their own server or use it from another open source project harmonoid-service).

After this change, this app will just be "A music player that can play audio files & acquire them from a server written in a very specific way according to requirement. User can write/use their own server. It's completely their choice if they choose node.js or Python to write it or they can already existent server at harmonoid-service"

This will make the app both PERSONAL & a app (AND NOT A SERVICE).

In simpler words, users now have to deploy/use their own server.

**Okay... So harmonoid is legal... but harmonoid-service is definitely illegal... What do you wanna say about that?**
No, it is not.
It's just a script written using youtube-dl & ytmusicapi, which both are for personal use. It is just another random GitHub project which hopefully works well as a server for harmonoid somehow (you know what I did there 😝).

**Well why did you make a server for app in the first place?**
It was "personal"... I didn't think this project will be used this widely.
I'm just using it with my friends (@mytja & @raitonoberu), so it is personal.

Look, IT WAS 100% POSSIBLE FOR ME TO MAKE HARMONOID FUNCTION WITHOUT ANY SERVER REQUIREMENT AT ALL. But, I don't wanted to compile a new APK everytime YouTube breaks something (updating server is easier).

I hope everyone gets what I mean.
Thankyou for using code of this random guy on GitHub.

**Apart from that, you people know that it's not a crime to just get music but, (just in case) I don't want legal organizations suing me.**

**Comment by alexmercerind** [comment]
😶 You can ask me anything regarding above.

**Comment by alexmercerind** [comment]
However, I'm yet to decide how the things should be. But in the above comment, I've told everything like ideally how it should be.

My personal servers however are:
- harmonoidservice: The stable vanilla Spotify one
- harmonoid: The one with YouTube music
- harmonoid-pc: The one with YouTube music & MP3 support

The future version of app (v0.0.3+) will only use YouTube music ones (or Spotify version needs some fixes) & will support both MP3 & M4A.
I don't think there is any use of Spotify one.
Rest is over people... If they wanna write their own server.

**Comment by mytja** [comment]
Okay, i'm a little confused, but i get your point. I will remove Readme changes and only use Slovenian language

**Pull request closed without merging**
