### PR TITLE
Added German language

### PR DESCRIPTION
**Pull request by mytja**

### CODE REVIEW

**Comment by alexmercerind** [comment]
Hi @mytja !

You speak German as well... great!

But, I've added bit more strings to each language. Can you update Slovenian & the one in this commit before the merge.

Thanks 😃

**Review by alexmercerind — APPROVED** [review]

**Comment by mytja** [comment]
Ummm.
I was doing some commits......
However, they aren't important (so much)
:pen:

**Comment by alexmercerind** [comment]
Oh dear... Seems I interrupted you.

**Comment by mytja** [comment]
https://github.com/mytja/harmonoid/commit/5392c6465df42cf554c3763fc4c6925ea14653e0

Here is a change in README.md

**Comment by alexmercerind** [comment]
Hi @mytja !

I just added a new pre-release.

You can download the new APK [here](https://github.com/alexmercerind/harmonoid/releases/download/v0.0.1%2B2/harmonoid-v0.0.1+2-pre-release.apk).

**Changelog:** https://github.com/alexmercerind/harmonoid/releases/tag/v0.0.1%2B2

**I hope this will greatly improve your app experience. It now has many improvements and translations provided by you.**

**Comment by mytja** [comment]
Hello!
I'm testing it, and it is awesome.
However, I'd like to ask you, what does a star right from my name in About section mean?
Thank you

**Comment by mytja** [comment]
@alexmercerind @raitonoberu I'm also testing async server on URL harmonoid-us.herokuapp.com
I think it is very well made. 😀
I'm going also to keep my EU (stable) and US (developement) servers online, since EU is closest to me, and US is a preview for stable version.
I think you made a very nice server code. Good job.

**Pull request merged**
