### PR TITLE
🖊 Updated German language by @MickLesk

### PR DESCRIPTION
**Pull request by alexmercerind**

### CODE REVIEW

**Review by alexmercerind — COMMENTED** [review]
globalsupdater.dart needs bit of change.

**Comment by alexmercerind** [comment]
@MickLesk It's not a big trouble for me but still can you remove the changes happening to other languages from your fork?

It can help me a little bit.

**Comment by MickLesk** [comment]
You mean that I only leave the German entries and remove the other languages from the .dart file?

**Comment by alexmercerind** [comment]
I mean if you look at the "Files Changed" of this pull request, you will notice that your this pull request is causing changes to other languages as well & not just German.
Thankyou.

**Comment by MickLesk** [comment]
Ah thats the Autobreak in visual Studio Code. :( I dont know how can i deactivate this shit...

**Comment by alexmercerind** [comment]
But I don't see the same [here](https://github.com/alexmercerind/harmonoid/pull/23/files). This is because my repository got updated when you were making the commits on top of old fork of it. Nevermind.

**Comment by alexmercerind** [comment]
Hi @MickLesk, 
I added the changes made by you in following commit:
alexmercerind@a6c55ad055b465ec7175068ab08f79b0b1a601d5

Don't worry, you are mentioned in the Harmonoid's about page & GitHub README.

❤ Thankyou.

**Pull request closed without merging**
