### PR TITLE
Improved german language

### PR DESCRIPTION
**Pull request by MickLesk**
But i dont know what STARGAZER it mean?

### CODE REVIEW

**Comment by MickLesk** [comment]
Change & Improve German Language

**Comment by alexmercerind** [comment]
Stargazers are the people "who starred the repository of this project". The app has a section in its about page, where I show them. One has to provide for that.

Let me know when I should merge this PR.
Thanks a lot for your contribution.

**Comment by alexmercerind** [comment]
You can download APK from release page for testing current German translation.
Sorry but I can't compile it for iOS 😓.

**Comment by MickLesk** [comment]
i build the project in the next hours, i give you feedback :P

**Comment by MickLesk** [comment]
i have improved the translation live @device. You can check & merge this. :-)

**Comment by alexmercerind** [comment]
Hi @MickLesk!
Apart from that, did everything work fine for you like the music downloads & playback?
In any case of problem, feel free to open issue.
The app is really in just a development phase right now and there is a FAQ at the end of readme if you feel confused in the UI of app.
Thanks!

**Comment by MickLesk** [comment]
Hey,

Yes the app is running fine, I did not get any error. But there are some things I would do "better". For example in the left task (now playing) if I "start" something there after restarting the app, nothing happens. Here a random playback would be quite nice, or that it saves the last "playback". In the collection (middle tab) at the top of the search bar I would take away the 3 |||, these tempt Android users to swip. Last searches are only written after leaving the page and reloading. Example I search for "Michael Jackson", then "Adele" then "Panic @Disco". This will not be displayed until the page is reopened.

Translated with www.DeepL.com/Translator (free version)

**Comment by alexmercerind** [comment]
No no! Don't open issues. I'll take care of your feedbacks. 
The three-lines button on the search bar is actually added for a future release (I have planned to add a drawer in the app). 
Since that search-bar is a custom widget made by me, I decided to keep everything in it ready for future. (I don't want to modify the code of it for just adding a drawer button in future.)
Yeah, "recent searches" have bit of problems right now.

This project is just more or less just my hobby. I just wanted to make a music app for myself that would have no ads and can download free music. So I decided to start working on this.

You can expect your features in upcoming releases (You can download APK for Android yourself there, without having to build yourself.).

Thankyou 😃!

**Pull request closed without merging**
