### PR TITLE
Update sl lang

### PR DESCRIPTION
**Pull request by mytja**
Forgot to translate 2 sentences.
😒

### CODE REVIEW

**Comment by alexmercerind** [comment]
Do you mind if I ask you to translate four more strings?
(I'm going to push in a minute).

**Comment by mytja** [comment]
Ok

**Comment by alexmercerind** [comment]
@mytja I have added some more strings at the end of each language. Please translate those as well. 😅

And, @raitonoberu... Can you open a new PR for Russian by translating those new strings please.

Thanks a lot ❤

**Comment by mytja** [comment]
Done

**Review by alexmercerind — COMMENTED** [review]
👌

**Pull request merged**
